config/routes.rb
Nest::Application.routes.draw do
  
  devise_for :users

  resources :jobs do
    resources :apps 
  end
  
  resources :apps do 
    resources :notes
  end

  resources :notes

  root :to => 'static_pages#home'
  match '/jobsindex', :to => 'jobs#index'
  match '/success', :to => 'apps#success'
  
  
  
  
  
  

end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :name, :email, :id, :app_id, :job_id, :question1_answer, :question2_answer, :resume, :coverletter, :transcript
  
  belongs_to :job
  has_many :notes
  
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false}
  
  
  has_attached_file :resume,
    :storage        => :s3,
    :bucket         => ENV['S3_BUCKET_NAME'],
    :s3_credentials => { :access_key_id      => ENV['S3_ACCESS_KEY'],
                         :secret_access_key  => ENV['S3_SECRET_KEY'] }

  has_attached_file :coverletter,
    :storage        => :s3,
    :bucket         => ENV['S3_BUCKET_NAME'],
    :s3_credentials => { :access_key_id      => ENV['S3_ACCESS_KEY'],
                         :secret_access_key  => ENV['S3_SECRET_KEY'] }
    
  has_attached_file :transcript,
    :storage        => :s3,
    :bucket         => ENV['S3_BUCKET_NAME'],
    :s3_credentials => { :access_key_id      => ENV['S3_ACCESS_KEY'],
                         :secret_access_key  => ENV['S3_SECRET_KEY'] }
    
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :title, :description, :question1, :question2
  
  has_many :apps
  has_many :notes, through: :apps
    
  belongs_to :user
  
  validates :title, presence: true
  validates :description, presence: true
  validates :question1, presence: true
  validates :question2, presence:true 
  
  

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :note, :comment, :app_id
  
  belongs_to :app

  validates :comment, presence: true
  validates :app_id, presence: true
  validates :user_id, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :jobs
  

  has_many :apps, through: :jobs
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include NotesHelper 
  
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController


def create
  @job = Job.find(params[:job_id])
  @app = @job.apps.build(params[:app])
  if @app.save
    redirect_to success_path
  else
    render 'new'
  end
end

def new
  @job = Job.find(params[:job_id])
  @app = @job.apps.build
end

#show page
def show
  
  @app = App.find(params[:id])  
  @note = @app.notes.build
  @feed = @app.notes.paginate(:page => params[:page], :per_page => 30)
  @status = App.find(params[:id])
  
end

#index
def index
  @job = Job.find(params[:job_id])
  #@app = @job.apps(:app => @app)

end





def update
end



def destroy
end

def success
end



end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

before_filter :authenticate_user!


# create new job
def create
  @job = current_user.jobs.create(params[:job])
  if @job.save
    flash[:success] = "Job Creation Successful!"
    redirect_to @job
  else
    render 'new'
  end
end

def new
  @job = current_user.jobs.new

end

#show page
def show
  @job = current_user.jobs.find(params[:id])
  @app = @job.apps.all
  @question1 = Job.find(params[:id]).question1
  
  
end

#index
def index
  @job = current_user.jobs.all
end

def edit
  @job = current_user.jobs.find(params[:id])
end

def update
  @job = current_user.jobs.find(params[:id])
  if @job.update_attributes(params[:job])
    flash[:success] = "Job Edit Successful!"
    redirect_to root_path
  end
end

def destroy
end






end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  def create
    #@something = params(:id)
    #@app = App.create(params[:app])
    #@app.app_id = params[:app][:id]
    
    #@app = params[:id]
    #@note = @app.notes.build(params[:note])  
    #@app= App.find(params[:id])    
        
    @app = App.find(params[:note][:app_id])
    @note = @app.notes.build(params[:note])
    @note.user_id = current_user.id
    @note.note = "remove column"
    if @note.save
        redirect_to @app
      else
        redirect_to @app
    end
  end  
  
  
  
  
  def new

   @note = @app.notes.new

    
    if @note.save
      redirect_to 'job_app'
    else
      redirect_to 'job_app'
    end

  end
  
  def show
  @note = Note.find(params[:id])
    
  end
  
  
  def update
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    #@write = Jobs.find(4).apps.find(4).notes.new
    @write = Note.new
    if user_signed_in?
      @listjobs = current_user.jobs.all
    end
  end
  
  
  
  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper




end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/notes_helper.rb
module NotesHelper

def noteshelper(id)

end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/apps/index.html.erb
<h1> Index Page </h1>
	
	<% @app.each do |form| %>
		<li>
	    	<%= link_to form.name  %>
			<%= link_to form.email%>
	    </li>
	<% end %>
	

app/views/apps/new.html.erb
<div class= "row">
	
	<div class="span6">
		<h3><%= @job.title %></h3>
		<%= @job.description %>
	</div>
	
	<div class="span6">
		<legend>Apply for Job</legend>
		
		<%= form_for [@job, @app], :html => {:class => "form-horizontal"} do |f| %>
		

			
			<p>
				<%= f.label "Name" %>
				<%= f.text_field :name %>
			</p>
			
			<p>
				<%= f.label "Email" %>
				<%= f.text_field :email %>
			</p>
			
			<p>
				<%= f.label @job.question1 %>
				<%= f.text_field :question1_answer %>
			</p>
			
			<p>
				<%= f.label @job.question2 %> 
				<%= f.text_field :question2_answer %>
			</p>
			
			<p>
				<%= f.label :coverletter %><%= f.file_field :coverletter %>
			</p>
			
			<p>
				<%= f.label :resume %><%= f.file_field :resume %>
			</p>
			<p>
				<%= f.label :transcript %><%= f.file_field :transcript %>
			</p>
			
				<%= f.submit "Submit Job Paramters"%>
			</p>
			
		<% end %>
		
	</div>
</div>

app/views/apps/show.html.erb
<div class="container">
	<div class="row">
		 <table>
			<tr>
				<td><b> Name:  </b> </td>
				<td> <%= @app.name %> </td> 
			</tr>
			<tr>
				<td><b> Email:  </b> </td>
				<td> <%= @app.email %> </td> 
			</tr>
			<tr>
				<td><b> Question 1:  </b> </td>
				<td> <%= @app.question1_answer %> </td> 
			</tr>
			<tr>
				<td><b> Question 2:  </b> </td>
				<td> <%= @app.question2_answer %> </td> 
			</tr>
			<tr>
				<td><b> Resume:  </b> </td>
				<td><%= link_to 'Click here', @app.resume.url %> </td> 
			</tr>
			<tr>
				<td><b> Cover Letter:  </b> </td>
				<td><%= link_to 'Click here', @app.coverletter.url %> </td> 
			</tr>
			<tr>
				<td><b> Academic Transcript:   </b> </td>
				<td><%= link_to 'Click here', @app.transcript.url %> </td> 
			</tr>
			<tr>
				<td><b> Status:   </b> </td>
				<td><%= @app.status %> </td> 
			</tr>
			
		</table>
		<%= render 'shared/status_form' %>
<p> </p>			
		<%= render 'shared/notes_form' %>
	</div>
	
	<div class="row">
		<% @feed.reverse_order.each do |present| %>
			<ul class="nav nav-pills nav-stacked">
				<li><%= present.comment %><li>
			</ul>
		<% end %>
	</div>
</div>

app/views/apps/success.html.erb
<h3> Thanks for your app! We'll be sending you an email just to double-confirm with you!</h3>

<p> Detail detail detail, eg, if you don't get this email please contact us to ensure! Many thanks for your time! </p> 

app/views/jobs/edit.html.erb
<legend>Edit Job</legend>

<%= form_for @job do |f| %>

	
	<p>
		<%= f.label "Job Name" %>
		<%= f.text_field :title%>
	</p>
	
	<p>
		<%= f.label "Job Description" %>
		<%= f.text_area :description, :style => "height:100px; width:400px;"%>
	</p>
	
	<p>
		<%= f.label "Question1" %>
		<%= f.text_area :question1, :style => "height:25px; width:400px;"%>
	</p>
	
	<p>
		<%= f.label "Question2" %>
		<%= f.text_area :question2, :style => "height:25px; width:400px;"%>
	</p>

		<%= f.submit "Update Job Parameters", :class => "btn"%>
	</p>
	
<% end %>

app/views/jobs/index.html.erb
<h3> Index Page </h3>
	
	<% @job.each do |form| %>
		<li>

	    	<%= link_to form.title, form %> | <%= link_to "View what the applicants see", new_job_app_path(form) %> | <%= link_to "Edit the Job", edit_job_path(form) %>

	    </li>
	<% end %>

app/views/jobs/new.html.erb
		<legend>Create Job</legend>
		
		<%= form_for @job do |f| %>
		
			
			<p>
				<%= f.label "Job Name" %>
				<%= f.text_field :title%>
			</p>
			
			<p>
				<%= f.label "Job Description" %>
				<%= f.text_area :description, :style => "height:100px; width:400px;"%>
			</p>
			
			<p>
				<%= f.label "Question1" %>
				<%= f.text_area :question1, :style => "height:25px; width:400px;"%>
			</p>
			
			<p>
				<%= f.label "Question2" %>
				<%= f.text_area :question2, :style => "height:25px; width:400px;"%>
			</p>
		
				<%= f.submit "Submit Job Paramters"%>
			</p>
			
		<% end %>
		

app/views/jobs/show.html.erb
<p> <b>Job Title:</b> <%= @job.title %> </p>
	
<b> Description: </b> <%= @job.description %>

<% @app.each do |form| %>
	<li>
    	<%= link_to form.name, form  %>
    </li>
<% end %>

app/views/layouts/_footer.html.erb
<div class="span12" style="height:50px; background-color:#c5c5c5; margin: 0px -20px 0px -20px;">
	Footer
</div>

app/views/layouts/_header.html.erb
<div class="row-fluid">
	
	<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
	<div class="span2">
				<%= link_to image_tag("jobpages.png"), root_path, :class => "brand", :style=>"margin-left:0px;" %>
	</div>
	<div class="span10">
		
	<ul class="nav nav-pills">

		
		
		
	</ul>
	
	<ul class="nav nav-pills" style="float:right">
		<li> <%= link_to('Help', ) %> </li> 
		<li> <%= link_to('Account Settings', edit_user_registration_path) %> </li> 
		<li> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>     		
	</ul>
	
		</div>
	</div>
	</div>
</div>
<div style="padding-top:40px;">
</div>

app/views/layouts/_sidebar.html.erb
<div style="background-color:#f7f4f4; height:800px; padding: 20px 20px 100px 10px; margin:0 0 0 -20px; border-right: 1px solid ; border-right-color:#b2b2b2; min-width:150px;">

		<ul class="nav nav-list">
		
			<li class="nav-header">General</li>
			<li><%= link_to "Home Page", root_path %></li>

			
			<li class="divider"></li>
			
			<li class="nav-header">Jobs</li>
			<li><%= link_to "Jobs Index", jobsindex_path %></li>
			<li><%= link_to('Create a job', new_job_path)%></li>
			<li><%= link_to "Dashboard", root_path %></li>
			
			<li class="divider"></li>
			
			<li class="nav-header">Application</li>
			<li><%= link_to "Dashboard", root_path %></li>
			<li><%= link_to "Dashboard", root_path %></li>
					
					
		</ul>	
		
		
										
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if signed_in? %>

		<div class="container-fluid">
			<%= render 'layouts/header'%>
			<div class= "row-fluid">
				<div class="span2">
					<%= render 'layouts/sidebar'%>
				</div>
				<div class="span10 mainarea">
					<% flash.each do |key, value| %>
					        <div class="alert alert-<%= key %>"><%= value %></div>
					<% end %>
					<%= yield %>
				</div>
			</div>
			
			<div class="row-fluid">
					<%= render 'layouts/footer'%>
			</div>
			
		</div>

	<% else %>
	
		<div class="container">
			<%= yield %>
		</div>

	<% end %>
	
	<% if Rails.env.development? %>
		<div class="container">
			</br></br>
			<%= debug (params)%>
		</div>
	<% end %>


</body>
</html>

app/views/notes/index.html.erb
index_remove later

<%= @app %>

app/views/notes/show.html.erb
<%= @note.comment %>

app/views/shared/_notes_form.html.erb
<%= form_for @note do |f| %>
	
	<%= f.hidden_field "app_id", :value => (params[:id]) %>
	<%= f.label "Note" %>
	<%= f.text_field :comment %>
	
	<%= f.submit %>
<% end %>

app/views/shared/_status_form.html.erb
<%= form_for @status do |f| %>
	<%= f.label :status %>
	<%= f.text_field :status %>
<%= f.submit %>
<% end %>

app/views/static_pages/_copywrite.html.erb
<div class="row">
	<div class="span12">
		<div class="copywrite" style ="height:200px; padding-top:20px;">
			
			<div class="main-sell" style="text-align:center">
				<p><h3>Quick & quality self-recruitment solutions.</h3></p>
				<p><h3>Spend less time managing forms and more time picking the right people</h3></p>
				<%= link_to "Sign In", new_user_session_path, :class => "btn"%>
				</br>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/_signedin.html.erb
<div style="height:100%;">
	
	<legend>
		<h4>Company Name Proxy</h4>
		<p>The mission statement of the company or goal of this div</p>
	</legend>
	<%= link_to('Create a job', new_job_path, :class => "btn btn-success")%>
	</br></br>
			

	<h4>Active Jobs</h4>

	<div class="well">
		<ul>
			<% @listjobs.each do |show| %>
				<div class="row">
					<li class="span12">
						<div>
							<strong><p><%= show.title %>  <%= link_to "Edit the Job", edit_job_path(show) %></p></strong>
							<p><%= show.description %></p>
							<p><%= link_to "see all applicants (click)", show %></p>
							<p><%= link_to "see the page prospects see", new_job_app_path(show) %></p>					
						</div>
						
						<div class="divider" style="width:100%;background-color:#D6D6D6;height:1px;margin:10px 0 20px 0;">
						</div>
						
					</li>
				</div>
			<% end %>
		</ul>
		
	</div>
</div>

app/views/static_pages/help.html.erb
<p>
	Insert Help documentation here
</p>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
	<%= render 'static_pages/signedin' %>
<% else %>
	<%= render 'static_pages/copywrite'%>
<% end %>